Financial-Times/annotations-rw-neo4j

README.md
app.go

Uses the service status library.
Will only be able to test in Jenkins when the code is merged!

Implement build info

---

annotations/cypher.go
annotations/cypher_test.go
app.go

Also cleaned up some of the code.

Added a GTG endpoint

---

annotations/model.go

Add major mentions predicate to allow V1 annotations for organisations to start to be written

Add major mentions predicate

---

README.md
circle.yml

Tests pass on circle ci :)
https://circleci.com/gh/Financial-Times/annotations-rw-neo4j/129

Updated circle file to uses ft/neo4j image

---

annotations/cypher.go
app.go
http_handler.go
queue_handler.go
vendor/vendor.json

It was using an old version of go-logger that had a non-consistent method of logging.

Updated the version of go-logger being used

---

healthcheck.go
helm/annotations-rw-neo4j/templates/deployment.yaml
helm/annotations-rw-neo4j/values.yaml
queue_handler_test.go
vendor/vendor.json

Needed for K8s work:
* healthcheck max 10s
* gtg check max 3s (already done)
* pod affinity
* memory limit (bonus: request)

Improved healthcheck + helm config 

---

README.md

Remove the deployment part

---

app.go
helm/annotations-rw-neo4j/app-configs/annotations-rw-neo4j_delivery.yaml
helm/annotations-rw-neo4j/app-configs/suggestions-rw-neo4j_delivery.yaml
helm/annotations-rw-neo4j/templates/deployment.yaml
vendor/vendor.json

- removed graphite integration

Remove graphite integration

---

.circleci/config.yml
annotations/cypher.go
app.go

- unreachable code
- lint warnings
- wrong return type
- unhandled type assertion

Linting, assertion fixes, neo4j test image update

---

helm/annotations-rw-neo4j/app-configs/annotations-rw-neo4j_eks_delivery.yaml
helm/annotations-rw-neo4j/app-configs/suggestions-rw-neo4j_eks_delivery.yaml
helm/annotations-rw-neo4j/templates/deployment.yaml
helm/annotations-rw-neo4j/values.yaml

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code
Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.
___

Add delivery EKS configd

---

annotations/cypher_integration_test.go

Clean up identifiers from integration tests
JIRA Ticket [UPPSF-2230](https://financialtimes.atlassian.net/browse/UPPSF-2230)
___

Clean up identifiers from integration tests

---

.circleci/config.yml
annotations/cypher.go
docker-compose-tests.yml
go.mod
go.sum

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code
Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.
___

Update cm-neo4j-driver to v1.1.0

---

healthcheck.go
helm/annotations-rw-neo4j/app-configs/annotations-rw-neo4j_eks_delivery.yaml
helm/annotations-rw-neo4j/app-configs/suggestions-rw-neo4j_eks_delivery.yaml
helm/annotations-rw-neo4j/templates/deployment.yaml
main.go

Add systemCode parameter to the service
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-3078)
___

Add systemCode parameter to the service

---

.circleci/config.yml
Dockerfile.tests
annotations/cypher.go
annotations/cypher_integration_test.go
docker-compose-tests.yml
forwarder/forwarder.go
forwarder/forwarder_test.go
http_handler.go
http_handler_test.go
mocks.go
queue_handler.go
queue_handler_test.go

Include Neo4j bookmarks in the Kafka messages it produces down the pipeline
JIRA Ticket [UPPSF-4226](https://financialtimes.atlassian.net/browse/UPPSF-4226)
___
[UPPSF-4226]: https://financialtimes.atlassian.net/browse/UPPSF-4226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 Include Neo4j bookmarks

---

README.md
annotations/cypher.go
annotations/cypher_integration_test.go
go.mod
go.sum
helm/annotations-rw-neo4j/templates/deployment.yaml
main.go

A little copying is better than a little dependency. The function is one-liner(alomst) and can be implemented by the service.
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-4238)
___

Remove the dependency on `neo-model-utils-go`.

---

schemas/annotations-next-video.json
schemas/annotations-pac.json
schemas/annotations-v2.json
schemas/predicates.json

Schemas for PAC, Next Video, V2 annotations and constraints for predicates and concept types
JIRA Ticket [UPPSF-4370](https://financialtimes.atlassian.net/browse/UPPSF-4370)
___
[UPPSF-4370]: https://financialtimes.atlassian.net/browse/UPPSF-4370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Schemas for PAC, Next Video and V2 annotations

---

go.mod
go.sum
schemas/annotations-pac.json

Extend the PAC annotations schema
JIRA Ticket [UPPSF-4614](https://financialtimes.atlassian.net/browse/UPPSF-4614)
___
[UPPSF-4614]: https://financialtimes.atlassian.net/browse/UPPSF-4614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extend the PAC annotations schema

---

annotation-config.json
annotations/cypher.go
annotations/cypher_integration_test.go
exampleAnnotationsMessage.json
go.mod
go.sum
helm/annotations-rw-neo4j/app-configs/annotations-rw-neo4j_eks_delivery.yaml
http_handler.go
http_handler_test.go
mocks.go
queue_handler.go
queue_handler_test.go
schemas/annotations-sv.json

Add support for publication field
JIRA Ticket [UPPSF-4657](https://financialtimes.atlassian.net/browse/UPPSF-4657)
___
[UPPSF-4657]: https://financialtimes.atlassian.net/browse/UPPSF-4657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add support for publication field

---

annotation-config.json

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code
Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.
___

add spark to the originMap

---

annotation-config.json

Change lifecycle and platform version for SV annotations
JIRA Ticket [UPPSF-4737](https://financialtimes.atlassian.net/browse/UPPSF-4737)
___
[UPPSF-4737]: https://financialtimes.atlassian.net/browse/UPPSF-4737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change lifecycle and platform version for SV annotations

---

schemas/annotations-sv.json

Add hasAuthor predicate to SV annotations schema
JIRA Ticket [UPPSF-4800](https://financialtimes.atlassian.net/browse/UPPSF-4800)
___
[UPPSF-4800]: https://financialtimes.atlassian.net/browse/UPPSF-4800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add hasAuthor predicate to SV annotations schema

---

go.mod
go.sum
schemas/annotations-sv.json

Updated cm-annotations-ontology and hasReference predicate
[JIRA](https://financialtimes.atlassian.net/browse/UPPSF-4890)
___

Updated cm-annotations-ontology and hasReference predicate
